# ------------------------------------------
#     App
# ------------------------------------------
#app:
#  name: ConfigServer
#  powered: Emiliano Quircio
#  date: xx/xx/2022

server:
  port: 8888

spring:
  config:
    use-legacy-processing: false

# ------------------------------------------
#     Profilo
# ------------------------------------------
#  profiles:
#   active: github


