# ------------------------------------------
# - Config Server
# - PROFILO GITHUB
# ------------------------------------------
spring:
  config:
    activate:
      on-profile: github


  application:
    name: ConfigServer

  cloud:
    config:
      #uri: http://localhost:8888
      #profile: test
      server:
      #  bootstrap: true
        git:
          uri: https://github.com/EmilianoQuircio/articoli-config.git
          clone-on-start: true
          #username:
          #password:
          default-label: master