# ------------------------------------------
# - Config Server
# - PROFILO GIT
# ------------------------------------------
spring:
  config:
    activate:
      on-profile: git
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: file:///C:\git-config-repository #file:///home/nicola/Documents/git-config-repository
          default-label: master #C:\Users\Emiliano Quircio\Documents\GitHub