# ------------------------------------------
#     App
# ------------------------------------------
app:
  name: ConfigServer
  powered: Emiliano Quircio
  date: xx/xx/2022

# ------------------------------------------
#     Edit Configuration -> Program Argument
#           ${admpsw} ${uspsw}
#         admpsw=admin;uspsw=user
# ------------------------------------------
sicurezza:
  adminpwd: ${admpsw}
  userpwd: ${uspsw}


server:
  port: 8888

spring:
  config:
    use-legacy-processing: false

# ------------------------------------------
#     Profilo
# ------------------------------------------
  profiles:
    active: github

# ------------------------------------------
#      LOGGING settings
# DEBUG - INFO - WARN - ERR
# ------------------------------------------
logging:
  level:
    root: WARN
