# ------------------------------------------
# - Config Server
# - PROFILO GITHUB
# ------------------------------------------
spring:
  config:
    activate:
      on-profile: github

# ------------------------------------------
  application:
    name: ConfigServer

# ------------------------------------------
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EmilianoQuircio/articoli-config.git
          username: EmilianoQuircio
          # Token di github
          password: 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
          timeout: 5
          cloneOnStart: true
          #default-label: master