# ------------------------------------------
# - Config Server
# - PROFILO GITHUB
# ------------------------------------------
spring:
  config:
    activate:
      on-profile: github

# ------------------------------------------
  application:
    name: CONFIG-SERVER

# ------------------------------------------
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EmilianoQuircio/articoli-config.git
          username: EmilianoQuircio
          # Token di github
          password: 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
          timeout: 5
          clone-on-start: true
          default-label: main