# ------------------------------------------
# - Config Server
# - PROFILO GIT
# ------------------------------------------
spring:
  config:
    activate:
      on-profile: git
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: file:///C:\Users\Emiliano Quircio\Documents\GitHub\git-config-repository
